# Generated by Django 4.2.21 on 2025-05-21 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría (ej: Sueldo, Comida, Transporte)', max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario si la categoría es personalizada, o nulo si es global.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del ingreso', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se recibió el ingreso')),
                ('source', models.CharField(blank=True, help_text='Fuente del ingreso (ej: Empleo X, Cliente Y)', max_length=100)),
                ('recurrence', models.CharField(choices=[('none', 'No Recurrente'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('annually', 'Anual')], default='none', help_text='Frecuencia de recurrencia del ingreso', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Descripción o notas adicionales sobre el ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría del ingreso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
